services:
  maria_db:
    image: mariadb:10.11
    container_name: flower-shop-mariadb-container
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    networks:
      flower-shop-network:
        ipv4_address: 192.168.1.10
    ports:
      - "1020:3306"
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: flower_shop
      MARIADB_USER: flower_shop_user
      MARIADB_PASSWORD: password
    volumes:
      - db_data:/var/lib/mariadb

volumes:
  db_data:

networks:
  flower-shop-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1